[build]
  command = "npm run build"
  functions = "functions"
  publish = "build"

[[redirects]]
  from = "/"
  to = "/.netlify/functions/repositories"
  status = 200

[[redirects]]
  from = '/*'
  to = '/.netlify/functions/:splat'
  status = 200
